### ISSUE TITLE
Which version of tvheadend does it support

### ISSUE THREAD

**Issue by bl4s7er** [pgaubatz/serviio-tvheadend-plugin#1]
I have tried both the stable release 3.4.27 and now 3.5.247~g098b7de~precise, but neither seems to allow for the http API calls? I just get a error message "1 Unknown returncode".

Can you update the readme to include more info about running this plugin. Thanks!

**Comment by pgaubatz** [comment]
Hi,

there have been quite a few changes to Tvheadend's HTTP API in v3.9.
Unfortunately, my plugin doesn't support anything older than Tvheadend v3.9...
So you might have to switch to the "unstable" repository (see, https://tvheadend.org/projects/tvheadend/wiki/AptRepository)

Cheers,
Patrick
