### ISSUE TITLE
Getting it to work

### ISSUE THREAD

**Issue by mattiasdh** [pgaubatz/serviio-tvheadend-plugin#2]
Hi, I'm unable to get this to work with Serviio 1.4.1.2 on a Synology DS414 (see http://pcloadletter.co.uk/2012/01/25/serviio-syno-package/ ). The log shows that the plugin does get loaded.

Do I have to change anything to the plugin? Like following line?
`def realTvheadendUrl = new URL("http://10.0.2.5:9981/tvheadend")`
Thanks in advance for your answer..!

**Comment by pgaubatz** [comment]
Hi,

you don't have to change anything in the source code!
Have you seen the [Instructions](https://github.com/pgaubatz/serviio-tvheadend-plugin/blob/master/README.md#instructions)?

Cheers,
Patrick

**Comment by mattiasdh** [comment]
Hi Patrick,

Yes, I followed the instructions, but failed to notice the 'incognito' part - I was already logged in.. :/
After I managed to set up a catch-all streaming + web interface access rule, everything is working as advertised!
You might like to add following link to your instructions, for noobs like me ;) 
https://www.tvheadend.org/projects/tvheadend/wiki/Access_configuration

Thanks for the great plugin, cheers!

**Comment by pgaubatz** [comment]
Hi,

thanks for the hint, I've just added the link to the readme!

Cheers,
Patrick
